### ISSUE TITLE
nvcc fatal error during installation on mac (2014 MBP)

### ISSUE THREAD

**Issue by shadowleaves** [cudamat/cudamat#39]
the following error was seen. it seems that setup.py was trying to compile using x86_64 architecture which isn't among the gpu-architecture. overriding setup.py with "NVCCFLAGS=-arch=sm_30 python setup.py install" didn't help.

nvcc --shared -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/cudamat/learn.o build/temp.macosx-10.5-x86_64-2.7/cudamat/learn_kernels.o -L/Users/hyan/anaconda/lib -lcublas -o build/lib.macosx-10.5-x86_64-2.7/cudamat/libcudalearn.so
nvcc fatal   : Value 'x86_64' is not defined for option 'gpu-architecture'

NVCC version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_19:13:24_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12

**Comment by tylerpayne** [comment]
I am having this error as well, also on a Macbook Pro with the Anaconda distribution of Python

**Comment by f0k** [comment]
Unfortunately, I don't have a Mac, so I cannot reproduce or fix the problem. Can one of you try to trace where the `-arch x86_64` is inserted into the linker line? I guess [`setuptools.command.build_ext`](http://svn.python.org/projects/sandbox/branches/setuptools-0.6/setuptools/command/build_ext.py) is the place to start digging, which in turn uses [`distutils.command.build_ext`](http://svn.python.org/projects/python/trunk/Lib/distutils/command/build_ext.py). Especially take a look at `build_extension()`, insert some print statements there to see what's going on or add a `import pdb; pdb.set_trace()` line to go into a debugging session and step through the code. If we know where the parameter comes from, we can see if and how to fix it in our `setup.py` file or in your environment configuration.

**Comment by scttl** [comment]
So it looks like this issue is either Anaconda distutils specific, or may have been fixed starting with distutils 2.7.9.

I didn't originally have Anaconda installed on my Mac and couldn't reproduce, but after installing it and using `~/anaconda/bin/python setup.py build` the `-arch x86_64` appears.

Using that, I traced through the calls and discovered that the arch stuff is being re-added during linking by distutils on line 197 of `anaconda/lib/python2.7/distutils/unixccompiler.py`:
```
195                 if sys.platform == 'darwin':                                                    
196                     linker = _osx_support.compiler_fixup(linker, ld_args)                       
197                     ld_args = ['-arch', 'x86_64'] + ld_args                                     
```

When I  compare this with my existing system version of distutils (v2.7.9), line 197 doesn't exist.  Under the Anaconda distribution, distutils.__version__ reports 2.7.8.

**Comment by f0k** [comment]
Very good, Watson! Now how do the `ld_args` find their way into the call that is executed in the end? Do you see a way to intercept this and replace it by `['-Xlinker', ','.join(ld_args)]` from within `setup.py`? (I think this syntax should work as well, i.e., `-Xlinker -arch,x86_64`.) Or is it possible to update the version of distutils used by anaconda? Then we could just mention this in the install instructions. The problem seems to be reasonably common to warrant being addressed in some way. Thank you for your help!

**Comment by scttl** [comment]
Yes, unfortunately the very next line to be executed is: `self.spawn(linker + ld_args)` which is what actually launches the subprocess.

We can play the dirty trick in setup.py of changing the linker_so executable to 'nvcc --shared -Xlinker' to get close to what we need (since this is what gets populated for the `linker` variable) but this still fails because we need to either wrap the `-arch x86_64` part in quotes, or inject `-Xlinker` in between these two parts.

Since distutils normally comes bundled with python, I'm not sure how/if we can independently update it?

**Comment by f0k** [comment]
Can we override `spawn`? If I follow the code correctly, you were looking at the `link` method of the `UnixCCompiler` class, which calls the `spawn` method of the base class (`CCompiler`), which in turn calls `distutils.spawn.spawn`. We should be able to monkey-patch `self.compiler.spawn` in our `setup.py` and modify the command line if needed. This wouldn't be very elegant, but if we do it right, it would help for any other extra linker or compiler arguments that `nvcc` needs to pass on instead of interpret itself (i.e., it might fix other problems than an old `distutils` on Mac).
